[WIP] set up a document information dictionary
gfngfn/SATySFi pull request #268
Opened 2021-04-19 05:48 UTC by puripuri2100

Solve #267 .

2021-04-20 12:57 UTC, gfngfn commented
Thank you for suggesting modification! Let me look into the implementation.

2021-04-20 13:01 UTC, gfngfn requested changes

2021-04-20 13:01 UTC, gfngfn commented on src/backend/documentInfomationDictionary.ml
> +type document_infomation_dictionary = {
Found a mis-spelling as an English word (`infomation` → `information`).

2021-04-20 13:05 UTC, gfngfn requested changes

2021-04-20 13:05 UTC, gfngfn commented on src/backend/documentInfomationDictionary.ml
> +    | lst -> [("/Keywords", Pdf.String (to_utf16be (sub lst "")))]
I think this can be done by `[("/Keywords", Pdf.String(to_utf16be (String.concat " " lst)))]` without using `sub`.

2021-04-21 08:30 UTC, puripuri2100 commented
I fixed.

2021-04-21 15:42 UTC, gfngfn commented
On a second thought during the trial to extend `page-break` with an optional argument, I have come to think that providing `set-document-information`, which you had first suggested, would be safer. The current formalization of how to handle primitives is very complicated, and thus it seems difficult and error-prone to extend primitives with optional arguments (although this situation should be solved as a distinct issue).

I am sorry for asking so much of you, but would you add `set-document-information` to `vminstdef.yaml` instead of extending `page-break`? (If not, I’m ready to do this by myself, of course.)

2021-04-22 00:39 UTC, puripuri2100 commented
I added `set-document-information` to `vminstdef.yaml`.

2021-04-22 01:14 UTC, puripuri2100 commented
Hmm...
Should I rename it to `register-document-information`, like `register-outline`?

2021-04-22 10:31 UTC, gfngfn commented
Thank you for the modification!

> Should I rename it to `register-document-information`, like `register-outline`?

It sounds nice! Both are acceptable to me, but I slightly prefer `register-*` to `set-*`. Feel free to rename the primitive if you will.

2021-04-22 11:36 UTC, puripuri2100 commented
It's all done!
Please merge at any time.

2021-04-22 20:54 UTC, gfngfn commented
Confirmed that the primitive works fine (by using it in `stdjabook.satyh` and `doc-primitives.saty`)!

<img width="745" alt="document information dictionary was successfully written in a PDF generated by SATySFi" src="https://user-images.githubusercontent.com/6876129/115783634-11284200-a3f8-11eb-9232-6a6188d8e9e4.png">

Thank you for the development!

2021-04-22 20:54 UTC, merged